// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class CommunityComment
{
    public int CommentId { get; set; }

    public int PostId { get; set; }

    public int UserId { get; set; }

    public string Body { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual CommunityPost Post { get; set; }

    public virtual User User { get; set; }
}