// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class DashboardMetric
{
    public int MetricId { get; set; }

    public int UserId { get; set; }

    public string MetricName { get; set; }

    public decimal MetricValue { get; set; }

    public DateTime LastUpdated { get; set; }

    public virtual User User { get; set; }
}