// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class RateRule
{
    public int RateRuleId { get; set; }

    public int UserId { get; set; }

    public string CurrencyPair { get; set; }

    public decimal TargetRate { get; set; }

    public string Condition { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}