// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class User
{
    public int UserId { get; set; }

    public string AuthProvider { get; set; }

    public string ProviderUserId { get; set; }

    public string DisplayName { get; set; }

    public string Email { get; set; }

    public string AvatarUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public virtual ICollection<CommunityComment> CommunityComments { get; set; } = new List<CommunityComment>();

    public virtual ICollection<CommunityPost> CommunityPosts { get; set; } = new List<CommunityPost>();

    public virtual ICollection<DashboardMetric> DashboardMetrics { get; set; } = new List<DashboardMetric>();

    public virtual ICollection<OptimizerConfig> OptimizerConfigs { get; set; } = new List<OptimizerConfig>();

    public virtual ICollection<RateRule> RateRules { get; set; } = new List<RateRule>();
}